In [1]:
import torch
print(torch.__version__)

2.7.0+cu118


### **Intro to Tensors** 

**Creating Tensors**

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#MATRIX
MATRIX = torch.tensor([[1 , 2],
                       [3 , 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
#Tensor
TENSOR = torch.tensor([[
    [1 , 2 , 3],
    [4 , 5 , 6],
    [7 , 8 , 9]
]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random Tensors**  
We've established tensors represent some form of data.  
  
And machine learning models such as neural networks manipulate and seek patterns within tensors.  
  
But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).  
  
Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.  
  
In essence:  
  
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...  

In [13]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3 , 4)
random_tensor

tensor([[0.3798, 0.1068, 0.1644, 0.9827],
        [0.6617, 0.5768, 0.7822, 0.9546],
        [0.1609, 0.8992, 0.8544, 0.8050]])

In [14]:
random_tensor.ndim

2

In [15]:
random_tensor.shape

torch.Size([3, 4])

In [16]:
#Random tensor with similar to shape of image tensor
random_image_tensor = torch.rand(size=(3,224,224))  #height,width,colour channels(R,G,B)

In [17]:
random_image_tensor

tensor([[[0.0456, 0.4214, 0.3694,  ..., 0.8640, 0.8219, 0.8910],
         [0.8760, 0.1626, 0.2297,  ..., 0.9387, 0.8654, 0.9901],
         [0.1357, 0.5308, 0.8181,  ..., 0.9417, 0.9130, 0.5553],
         ...,
         [0.5530, 0.7742, 0.8497,  ..., 0.7511, 0.1936, 0.3892],
         [0.9904, 0.6786, 0.9995,  ..., 0.8355, 0.0337, 0.7237],
         [0.0189, 0.4294, 0.3349,  ..., 0.4111, 0.3714, 0.2915]],

        [[0.8640, 0.4119, 0.7333,  ..., 0.5668, 0.2415, 0.2179],
         [0.7553, 0.6281, 0.5142,  ..., 0.4723, 0.0261, 0.4117],
         [0.3659, 0.7732, 0.5649,  ..., 0.6857, 0.3165, 0.3643],
         ...,
         [0.2484, 0.1091, 0.6299,  ..., 0.3825, 0.1529, 0.5347],
         [0.2287, 0.9320, 0.7485,  ..., 0.6546, 0.6225, 0.2594],
         [0.8393, 0.6147, 0.9840,  ..., 0.5801, 0.2359, 0.7625]],

        [[0.6940, 0.3195, 0.6369,  ..., 0.3358, 0.9575, 0.0341],
         [0.6430, 0.9871, 0.4790,  ..., 0.0563, 0.0435, 0.4154],
         [0.6277, 0.0870, 0.1556,  ..., 0.0538, 0.6734, 0.

Example:  
![Failed To Load](./images/img16.png)

**Zeros and Ones**

In [18]:
#Creating a tensor of all zeros 
zeros = torch.zeros((3,4))

In [19]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Creating a tensor of all ones 
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
#The default data type is float
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

In [22]:
ones = torch.ones(size = (3,4), dtype=torch.int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

**Creating Range of Tensors and Tensors-Like**

In [23]:
#Using torch.arange()
one_to_ten = torch.arange(0 , 11)
one_to_ten  

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
tensor_range = torch.arange(start = 0, end = 1000, step = 100)
tensor_range

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [25]:
#Creating tensors like
zero_tens = torch.zeros_like(input = one_to_ten) # Same shape like input
zero_tens

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor Datatypes**

In [26]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float32,  #Higher precision, slower computation
                               device = None,   #What device is your tensor on
                               requires_grad= False  #Whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
#Or you can specify params:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= torch.float16, 
                               device = None,  
                               requires_grad= False  
                               )
float_16_tensor.dtype

torch.float16

### **Getting Information from Tensors**  
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.  
  
We've seen these before but three of the most common attributes you'll want to find out about tensors are:  
  
`shape` - what shape is the tensor? (some operations require specific shape rules)  
`dtype` - what datatype are the elements within the tensor stored in?  
`device` - what device is the tensor stored on? (usually GPU or CPU)  
Let's create a random tensor and find out details about it.  

In [30]:
#Create random tensor
some_tensor = torch.rand(3,3)

print(some_tensor)

print(f"The shape of tensor is : {some_tensor.shape}")
print(f"The device of tensor is : {some_tensor.device}")
print(f"The datatype of tensor is : {some_tensor.dtype}")

tensor([[0.6029, 0.6689, 0.3500],
        [0.8158, 0.5999, 0.1139],
        [0.2203, 0.3269, 0.9281]])
The shape of tensor is : torch.Size([3, 3])
The device of tensor is : cpu
The datatype of tensor is : torch.float32


### **Manipulating Tensors**  
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.  
  
A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors   to create a representation of the patterns in the input data.  
  
These operations are often a wonderful dance between:  
  
Addition  
Substraction  
Multiplication (element-wise)  
Division  
Matrix multiplication  
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.  
  
Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).  

**Basic Operations**

In [31]:
#Create a tensor and add 10 to them
tensor = torch.tensor([1 , 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
#Create a tensor and multiply by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
#Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
#Using inbuilt functions
torch.add(tensor , 10 
          )

tensor([11, 12, 13])

**Matrix Multiplication**  
  
Main ways of performing matrix multiplication:  
  
**1. Element wise multiplication**

In [36]:
#Element wise operation

print(tensor , "*" , tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [37]:
torch.matmul(tensor, tensor)

tensor(14)

**2. Matrix multiplication**  
PyTorch implements matrix multiplication functionality in the torch.matmul() method.  
  
The main two rules for matrix multiplication to remember are:  
  
The inner dimensions must match:  
`(3, 2) @ (3, 2)` won't work  
`(2, 3) @ (3, 2) `will work  
`(3, 2) @ (2, 3)` will work  
The resulting matrix has the shape of the outer dimensions:   
`(2, 3) @ (3, 2) -> (2, 2) `   
`(3, 2) @ (2, 3) -> (3, 3) `  
> Note: "@" in Python is the symbol for matrix multiplication.  
> Note: One of the most common errors in deep learning: shape errors

In [38]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1 , 2 ],
    [3 , 4 ],
    [5 , 6 ]
])

tensor_B = torch.tensor([
    [7 , 10],
    [8 , 11],
    [9 , 12]
])

# torch.mm(tensor_A , tensor_B)  # torch.mm is the same as torch.matmul()
torch.matmul(tensor_A ,  tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.  
  
One of the ways to do this is with a transpose (switch the dimensions of a given tensor).  
  
You can perform transposes in PyTorch using either:  
  
1. torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.  
2. tensor.T - where tensor is the desired tensor to transpose. 
   
Let's try the latter.  

In [40]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [41]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


**Tensor Aggregation (min, max, sum etc)**

In [42]:
#Create a tensor
x =  torch.arange(0, 100, 10)
x , x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [43]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [44]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Positional min/max  
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.  
  
This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself  

In [45]:
#Crate a tensor
tensor = torch.arange(10 , 100 , 10)
print(f"Tensor : {tensor}")

# Returns index of max and min values
print(f"Index where the min value occurs {tensor.argmin()}")
print(f"Index where the max value occurs {tensor.argmax()}")

Tensor : tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where the min value occurs 0
Index where the max value occurs 8


Change tensor datatype  
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.  
  
If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.  
  
But there's a fix.  
  
You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is   the datatype you'd like to use.  
  
First we'll create a tensor and check its datatype (the default is torch.float32).  

In [46]:
#Creating a tensor by default
tensor = torch.arange(10. , 100. , 10.)
tensor.dtype

torch.float32

In [47]:
#Now we'll create another tensor the same as before but change its datatype to torch.float16
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [48]:
# And we can do something similar to make a torch.int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors. 

Let's try them out.

In [49]:
#Lets create a tensor
x = torch.arange(0 , 10)
x , x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [50]:
#Add an extra dimention
x_reshaped = x.reshape(1 , 10)
x_reshaped, x_reshaped.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [51]:
#Change the view
z = x.view(1,10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.  
  
So changing the view changes the original tensor too.  

In [52]:
z[:,0] = 5
z , x

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [53]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5, 5, 5, 5],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [54]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
# torch.squeeze() -  removes all single dimentions from a target tensor
print(f"Previous Tensor {x_reshaped}")
print(f"Previous Tensor Shape {x_reshaped.shape}")

#Remove extra dimension
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous Tensor tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous Tensor Shape torch.Size([1, 10])

New tensor: tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

New shape: torch.Size([10])


In [60]:
#torch.unsqueeze - adds a single dimention to target tensor at specific dim 
print(f"Previous Traget {x_squeezed}")
print(f"Previous Traget Shape {x_squeezed.shape}")

#Add extra dimension with unsqueeze
x_unsqeezed = x_squeezed.unsqueeze(dim = 0)
print(f"New Tensor {x_unsqeezed}")
print(f"New Tensor Shape {x_unsqeezed.shape}")

Previous Traget tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous Traget Shape torch.Size([10])
New Tensor tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
New Tensor Shape torch.Size([1, 10])


In [63]:
#You can also rearrange the order of axes values with torch.permute(input, dims)
x_original = torch.rand(size = (244,244,3))

#Permute the original tensor to rearrange dims
x_permuted = x_original.permute(2, 0 ,1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


> Note: Permuted and original share the same memory

### **Indexing (selecting data from tensors)**   
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).  
  
To do so, you can use indexing.  
  
If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.  

In [64]:
#Create tensor
x = torch.arange(1 , 10).reshape(1,3,3)
x ,  x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
#Indexing values goes outer dimension -> inner dimension (check out the square brackets).

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [66]:
#You can also use : to specify "all values in this dimension" 
# and then use a comma (,) to add another dimension.

# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])